---
- name: Ensure /opt/salarium exists
  file:
    path: /opt/salarium
    state: directory
    owner: {{ username }}
    group: {{ group }}
    mode: '0755'

- name: Copy salarium-in script
  ansible.builtin.copy:
    src: files/salarium-in.py
    dest: /opt/salarium/salarium-in.py
    owner: {{ username }}
    group: {{ group }}
    mode: '0644'

- name: Copy salarium-out script
  ansible.builtin.copy:
    src: files/salarium-out.py
    dest: /opt/salarium/salarium-out.py
    owner: {{ username }}
    group: {{ group }}
    mode: '0644'

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: files/requirements.txt
    dest: /opt/salarium/requirements.txt
    owner: {{ username }}
    group: {{ group }}
    mode: '0644'

- name: Install virtualenv
  ansible.builtin.apt:
    name: virtualenv
    state: latest
    install_recommends: false

- name: Install specified python requirements in indicated (virtualenv)
  ansible.builtin.pip:
    requirements: /opt/salarium/requirements.txt
    virtualenv: /opt/salarium/venv
  become: false